name: Frontend CI/CD
on:
  push:
    paths: ['EAD_FE_CA2/**']
    branches: [main]
  pull_request:
    paths: ['EAD_FE_CA2/**']
permissions:
  contents: read
  packages: write
  security-events: write
env:
  IMAGE: ghcr.io/nilavanluna/ead-ca2-2026/ead-ca2-fe
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: cd EAD_FE_CA2 && npm ci && npm test || true
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./EAD_FE_CA2
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
